apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx-multitool
  namespace: hw2-3
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello Kubernetes</title>
    </head>
    <body>
        <h1>Hello from Nginx in Kubernetes!</h1>
        <p>Howdy, fellas!</p>
    </body>
    </html>
  HTTP-PORT: "8082"
