apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: syslog-reader
spec:
  selector:
    matchLabels:
      app: syslog-reader
  template:
    metadata:
      labels:
        app: syslog-reader
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["sh", "-c", "tail -f /host-var-log/syslog"]
        volumeMounts:
        - name: host-log
          mountPath: /host-var-log/syslog
          subPath: syslog
      volumes:
      - name: host-log
        hostPath:
          path: /var/log
          type: Directory
